### ISSUE TITLE
Corresponding census markers for the shape files

### ISSUE THREAD

**Issue by makkunda** [justinelliotmeyers/official_india_2011_village_boundary_polygons_BHUVAN_2#3]
The shapefiles do not have any associated village markers as all the id columns have the entry None.Would it be possible to get some markers so maybe we could link the shape files to the census data ?

**Comment by justinelliotmeyers** [comment]
@makkunda sorry, this is the way the data came. If you want to link the census data to the gis data,you would need to build a relationship table.
